[tool.black]
line-length = 79

[tool.pytest.ini_options]
pythonpath = ['.']
filterwarnings = [
  'ignore:Python runners and associated APIs are an experimental feature and subject to change.:UserWarning',
]

[tool.ruff]
line-length = 79

[tool.tomlsort]
in_place = true
trailing_comma_inline_array = true
