excludes = [
  "*.lock",
  ".gitignore",
  "LICENSE",
]

[formatter.md]
command = "mdformat"
options = [
  "--number",
  "--wrap",
  "72",
]
includes = ["*.md"]

[formatter.nix]
command = "nix"
options = ["fmt"]
includes = ["*.nix"]

[formatter.py]
command = "black"
options = [
  "--line-length",
  "79",
]
includes = [
  "*.py",
]

[formatter.py-lint]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[formatter.sh]
command = "shfmt"
options = [
  "--write",
  "--binary-next-line",
  "--space-redirects",
  "--func-next-line",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml]
command = "toml-sort"
options = [
  "--in-place",
  "--trailing-comma-inline-array",
]
includes = ["*.toml"]

[formatter.yaml]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
]
