excludes = [
  "*.lock",
  ".gitignore",
  "LICENSE",
]

[formatter.md]
command = "mdformat"
options = [
  "--number",
  "--wrap",
  "72",
]
includes = ["*.md"]

[formatter.nix]
command = "nix"
options = ["fmt"]
includes = ["*.nix"]

[formatter.py]
command = "black"
options = [
  "--line-length",
  "79",
]
includes = [
  "*.py",
]

[formatter.py-lint]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[formatter.sh]
command = "shfmt"
options = [
  "--write",
  "--binary-next-line",
  "--space-redirects",
  "--func-next-line",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml]
command = "toml-sort"
options = [
  "--in-place",
  "--trailing-comma-inline-array",
]
includes = ["*.toml"]

[formatter.v]
command = "verible-verilog-format"
options = [
  "--column_limit=79",
  "--assignment_statement_alignment=align",
  "--case_items_alignment=align",
  "--class_member_variable_alignment=align",
  "--distribution_items_alignment=align",
  "--enum_assignment_statement_alignment=align",
  "--formal_parameters_alignment=align",
  "--formal_parameters_indentation=indent",
  "--module_net_variable_alignment=align",
  "--named_parameter_alignment=align",
  "--named_parameter_indentation=indent",
  "--named_port_alignment=align",
  "--named_port_indentation=indent",
  "--port_declarations_alignment=align",
  "--port_declarations_indentation=indent",
  "--struct_union_members_alignment=align",
  "--try_wrap_long_lines=true",
  "--inplace=true",
]
includes = [
  "*.v",
  "*.vh",
]

[formatter.yaml]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
]
