excludes = [
  "*.lock",
  "LICENSE",
]

[formatter.md]
command = "mdformat"
options = [
  "--number",
  "--wrap",
  "72",
]
includes = ["*.md"]

[formatter.nix]
command = "nix"
options = ["fmt"]
includes = ["*.nix"]

[formatter.toml]
command = "toml-sort"
options = [
  "--in-place",
  "--trailing-comma-inline-array",
]
includes = ["*.toml"]
