[formatter.black]
command = "black"
includes = [
  "*.py",
]

[formatter.mdformat]
command = "mdformat"
includes = [
  "*.md",
]

[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.ruff]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[formatter.shfmt]
command = "shfmt"
options = [
  "--write",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml-sort]
command = "toml-sort"
includes = [
  "*.toml",
]

[formatter.verible-verilog-format]
command = "verible-verilog-format"
options = [
  "--flagfile=.verible-verilog-format",
]
includes = [
  "*.v",
  "*.vh",
]

[formatter.verible-verilog-lint]
command = "verible-verilog-lint"
options = [
  "--flagfile=.verible-verilog-lint",
]
includes = [
  "*.v",
  "*.vh",
]

[formatter.yamlfmt]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
]

[formatter.yamllint]
command = "yamllint"
includes = [
  "*.yaml",
  "*.yml",
]

[global]
excludes = [
  "*.lock",
  ".editorconfig",
  ".gitignore",
  ".verible-verilog-format",
  ".verible-verilog-lint",
  "LICENSE",
]
