// SPDX-License-Identifier: MPL-2.0
//
// alu_ctrl.vh -- definition of ALU control signals
// Copyright (C) 2025  Andy Jaku <andyjaku13@gmail.com>

`ifndef KEEN_INSTRUCTION_SET_MAINDEC
`define KEEN_INSTRUCTION_SET_MAINDEC

// verilog_format: off

`define KEEN_INSTRUCTION_SET_MAINDEC_BRANCH_INACTIVE  1'b0
`define KEEN_INSTRUCTION_SET_MAINDEC_BRANCH_ACTIVE    1'b1

`define KEEN_INSTRUCTION_SET_MAINDEC_JUMP_INACTIVE  1'b0
`define KEEN_INSTRUCTION_SET_MAINDEC_JUMP_ACTIVE    1'b1

`define KEEN_INSTRUCTION_SET_MAINDEC_RESULT_SRC_ALU  2'b00
`define KEEN_INSTRUCTION_SET_MAINDEC_RESULT_SRC_DMEM 2'b01
`define KEEN_INSTRUCTION_SET_MAINDEC_RESULT_SRC_PCP4 2'b10

`define KEEN_INSTRUCTION_SET_MAINDEC_MEM_WRITE_INACTIVE 1'b0
`define KEEN_INSTRUCTION_SET_MAINDEC_MEM_WRITE_ACTIVE   1'b1

`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_ADD   4'b0000
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SLT   4'b0001
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SLTU  4'b0010
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_AND   4'b0011
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_OR    4'b0100
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_XOR   4'b0101
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SLL   4'b0110
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SRL   4'b0111
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SRA   4'b1000
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SUB   4'b1001
// Not formally defined within ISA
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SGT   4'b1010
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_CTRL_SGTU  4'b1011

`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_SRC_REGFILE  1'b0
`define KEEN_INSTRUCTION_SET_MAINDEC_ALU_SRC_SIGN_EXT 1'b1

`define KEEN_INSTRUCTION_SET_MAINDEC_IMM_SRC_ITYPE    2'b00
`define KEEN_INSTRUCTION_SET_MAINDEC_IMM_SRC_STYPE    2'b01
`define KEEN_INSTRUCTION_SET_MAINDEC_IMM_SRC_BTYPE    2'b10
`define KEEN_INSTRUCTION_SET_MAINDEC_IMM_SRC_JTYPE    2'b11

`define KEEN_INSTRUCTION_SET_MAINDEC_REG_WRITE_INACTIVE 1'b0
`define KEEN_INSTRUCTION_SET_MAINDEC_REG_WRITE_ACTIVE   1'b1


`endif  // KEEN_INSTRUCTION_SET_MAINDEC
